env:
	python3 -m venv .venv

activate:
	@echo "Run this in your shell instead: source .venv/bin/activate"

deactivate:
	@echo "Run this in your shell instead: deactivate"

install:
	pip3 install -r requirements.txt

install-dev:
	pip3 install -r requirements-dev.txt

start:
	python3 src/main.py