[project]
name = "jira-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.14"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.12.0",
    "requests>=2.32.4",
]

[project.scripts]
main = "src.main:main"
